[package]
name = "ssh-agent-client-rs"
version = "0.4.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nresare/ssh-agent-client-rs"
description = """
Pure rust implementation of the ssh-agent protocol. It can be used to write clients that interact with the ssh agent.
"""
edition = "2021"

[dependencies]
bytes = "1.4.0"
ssh-key = { version = "0.5.1", features = ["rsa", "dsa", "ed25519", "ecdsa", "p256", "p384"] }
ssh-encoding = "0.1.0"
# we need the signature that ssh-key uses
signature = "1.6.4"

[dev-dependencies]
getrandom = "0.2.9"
